### ISSUE TITLE
 You can mark the path "stylis" as external to exclude it from the bundle, which will remove this   error

### ISSUE THREAD

**Issue by jaekwanAHN** [tooooo1/dust-rating#23]
![image](https://user-images.githubusercontent.com/12118892/229303444-b046ac22-ee12-42d2-8862-cc6c701a5180.png)
최신 상태로 package json 을 업데이트하였으나 다음과 같은 에러가 발생하여
```npm i stylis```
을 통하여 해결하였으나 정상적인 해결방법인지 궁금합니다.

**Comment by tooooo1** [comment]
지금확인했네요! 의존성문제같아요. npm i 를 통해 해결하기보다 styled-compoenents에서 emotion으로 변경하면서 생긴 문제같은데 node_modules를 지우고 다시 설치하면 해결 될 것 같아요.
